using Grokomatic.Models;
using Newtonsoft.Json;
using System.Text;
using Grokomatic.Services;
using Grokomatic;

string openAiApiKey;
string grokApiKey;
string basePath;
string txtFile;
string pngFile;
string jpgFile;

try
{
    Initialize();

    string postText = GeneratePost();
    File.WriteAllText(txtFile, postText);

    string imagePrompt = GenerateImagePrompt(postText);
    
    await GenerateImage(imagePrompt, pngFile);

    Utilities.ConvertPngToJpg(pngFile, jpgFile, 80);

    // Post text and picture on X
    // Post text and picture on Facebook
    // Append selected innovation to list of completions and write to Completions file
}
catch (Exception ex)
{
    Console.WriteLine($"An error occurred: {ex.Message}");
}

void Initialize()
{
    openAiApiKey = Utilities.GetEnvironmentVariable("OPENAI_API_KEY");
    grokApiKey = Utilities.GetEnvironmentVariable("GROK_API_KEY");

    basePath = $@"{Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)}\Grokomatic";
    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
    
    if (!Directory.Exists(basePath))
    {
        Directory.CreateDirectory(basePath);
    }

    txtFile = Path.Combine(basePath, $"{fileName}.txt");
    pngFile = Path.Combine(basePath, $"{fileName}.png");
    jpgFile = Path.Combine(basePath, $"{fileName}.jpg");
}

string GeneratePost()
{
    string innovationsPath = "Data/Innovations.json";
    string completionsPath = "Data/Completions.json";

    List<TechInnovation> innovationsPool = Utilities.ReadJsonFile(innovationsPath);
    List<TechInnovation> previouslyPosted = Utilities.ReadJsonFile(completionsPath);
    List<TechInnovation> remainingInnovations = innovationsPool.Except(previouslyPosted).ToList();

    if (remainingInnovations.Count == 0)
    {
        Console.WriteLine("All innovations have been posted. No new posts available.");
        return string.Empty;
    }

    int randomNumber = Utilities.PickRandomNumber(remainingInnovations.Count - 1);
    TechInnovation selectedInnovation = remainingInnovations[randomNumber - 1];

    StringBuilder systemStringBuilder = new StringBuilder();
    systemStringBuilder.Append("You are a helpful assistant that creates social media post based on the user's request.");
    systemStringBuilder.Append("The post should be interesting, fun, accurate information");    
    systemStringBuilder.Append("It should contain appropriate hashtags including #TigerTriangleTechnology");
    systemStringBuilder.Append("Include fun facts. Feel free to strategically place an emoji where appropriate.");
    systemStringBuilder.Append("It should be ready to post as is and be in the format of a social media post with no additional instructions.");

    string userPrompt = $"Please generate text for a single post on social media about {selectedInnovation.Name} ({selectedInnovation.Description}) within the {selectedInnovation.Category} category.";

    string finePrint = "\n\nThis post was generated by AI as an experiment. It may contain errors or inaccuracies. Please feel free to fact check and/or leave a comment on how you think it did. Thanks!";

    var textGenerator = new GrokTextService();
    string textForPost = $"{textGenerator.GenerateText(systemStringBuilder.ToString(), userPrompt, grokApiKey)}{finePrint}";

    // Add selected innovation to the previouslyPosted list
    previouslyPosted.Add(selectedInnovation);

    // Write serialized list of previouslyPosted to completions file in JSON format
    File.WriteAllText(completionsPath, JsonConvert.SerializeObject(previouslyPosted, Formatting.Indented));

    Console.WriteLine("[ASSISTANT]");
    Console.WriteLine(textForPost);
    return textForPost;
}

string GenerateImagePrompt(string rawText)
{
    StringBuilder systemStringBuilder = new StringBuilder();
    systemStringBuilder.Append("You are a helpful assistant that generates a single image prompt for an AI image generator.");
    systemStringBuilder.Append("It will based on text given by the user.");
    systemStringBuilder.Append("It will be passed directly to a model to generate the image.");

    var textGenerator = new GrokTextService();
    string imagePrompt = textGenerator.GenerateText(systemStringBuilder.ToString(), rawText, grokApiKey);

    Console.WriteLine("[ASSISTANT]");
    Console.WriteLine(imagePrompt);
    return imagePrompt;
}

async Task GenerateImage(string imagePrompt, string filePath)
{
    if (string.IsNullOrEmpty(imagePrompt))
    {
        throw new ArgumentNullException(nameof(imagePrompt));
    }    

    var imageGenerator = new OpenAiImageService();
    try
    {
        await imageGenerator.GenerateImage(imagePrompt, filePath, openAiApiKey);
        Console.WriteLine($"Image generated successfully and saved to {filePath}");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"An error occurred while generating the image: {ex.Message}");
    }
}

